### ISSUE TITLE
Travis CI not supported anymore

### ISSUE THREAD

**Issue by msom** [seantis/libres#16]
@Daverball Can we test and deploy to pypi with github actions?

**Comment by Daverball** [comment]
@msom Yes, this is pretty straightforward. You can have a look at the pytest-codecov or AIS2.py repository to see how it's setup, both of those repositories are using tox for testing and have a deployment workflow that deploys to pypi.

So you can pretty much copy paste the .github Folder from either of those repositories with minor changes. (the PR specific workflow is only really needed if you want to upload code coverage results since PRs will not have access to the repository secrets and thus cannot upload coverage results) All you really need beyond that is to add repository secrets (generate a pypi token that has permissions to upload this specific package and generate a codecov token for this repository)
